"""
Multi-channel readout script for PRISM pipeline.

This script performs:
1. Spot detection using spotiflow (or traditional methods) on stitched images
2. Intensity extraction using tophat+3x3max method
3. Deduplication across all channels
4. Outputs separate position.csv and intensity.csv files

The output files are designed to work with the gene_calling pipeline:
- position.csv: Contains Y, X coordinates with index
- intensity.csv: Contains intensity values for all channels with matching index
- mapping.csv: Will be generated by gene_calling.py
"""

import os
import sys
import shutil
from pathlib import Path
import numpy as np
import pandas as pd
import yaml
from tqdm import tqdm
import tifffile
import logging
from concurrent.futures import ProcessPoolExecutor

# Add PRISM code path
package_path = 'path_to_PRISM_code_src'
if package_path not in sys.path:
    sys.path.append(package_path)

from readout.spot_detection import get_spot_coordinates
from readout.intensity_readout import read_intensity_tophat
from readout.deduplicate import deduplicate_dataframe

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ========== Configuration ==========
# Constants - modify these for your dataset
CHANNELS = ['cy5', 'TxRed', 'cy3', 'FAM']  # PRISM channels
BASE_DIR = Path('path_to_processed_dataset')
RUN_ID = 'example_data'
PRISM_PANEL = 'PRISM30'

# Paths
src_dir = BASE_DIR / RUN_ID
stc_dir = src_dir / 'stitched'
read_dir = src_dir / 'readout'
read_dir.mkdir(exist_ok=True)

# Detection parameters
DETECTION_METHOD = 'spotiflow'  # 'spotiflow', 'gaussian_tophat', or 'tophat'
DETECTION_SNR = {'cy5': 8.0, 'TxRed': 8.0, 'cy3': 8.0, 'FAM': 8.0}  # For traditional methods

# Intensity reading parameters
INTENSITY_METHOD = 'tophat'  # 'tophat' (recommended) or 'raw'
TOPHAT_RADIUS = 3
SEARCH_RADIUS = 1  # 3x3max (2*1+1 = 3)

# Deduplication parameters
DEDUP_THRESHOLD = 2  # Distance threshold for deduplication (pixels)


def _detect_spots_in_channel(args):
    """Helper function for parallel spot detection."""
    image_path, channel, method, method_kwargs = args
    try:
        image = tifffile.imread(str(image_path))
        coords = get_spot_coordinates(image, method=method, min_distance=2, **method_kwargs)
        return (channel, coords, None)
    except Exception as e:
        return (channel, np.empty((0, 2), dtype=np.float32), str(e))


def main(stc_dir=stc_dir, read_dir=read_dir, PRISM_PANEL='PRISM30'):
    """
    Main function for multi-channel readout.
    
    Parameters
    ----------
    stc_dir : Path
        Directory containing stitched images (cyc_1_channel.tif)
    read_dir : Path
        Output directory for readout results
    PRISM_PANEL : str
        PRISM panel type (PRISM30, PRISM45, etc.)
    """
    logger.info("=" * 80)
    logger.info("PRISM Multi-Channel Readout Pipeline")
    logger.info("=" * 80)
    logger.info(f"RUN_ID: {RUN_ID}")
    logger.info(f"PRISM_PANEL: {PRISM_PANEL}")
    logger.info(f"Detection method: {DETECTION_METHOD}")
    logger.info(f"Intensity method: {INTENSITY_METHOD} (tophat_radius={TOPHAT_RADIUS}, search_radius={SEARCH_RADIUS})")
    logger.info("=" * 80)
    
    # Stage 1: Spot Detection
    logger.info("=" * 80)
    logger.info("Stage 1: Spot Detection")
    logger.info("=" * 80)
    
    # Collect all channel images for detection
    detection_tasks = []
    for channel in CHANNELS:
        image_path = stc_dir / f'cyc_1_{channel}.tif'
        if not image_path.exists():
            logger.warning(f"Channel file not found: {image_path}, skipping...")
            continue
        
        # Prepare detection kwargs
        if DETECTION_METHOD == 'spotiflow':
            detection_kwargs = {
                'prob_thresh': 0.2,
                'device': 'cuda'  # or 'cpu'
            }
        else:
            detection_kwargs = {
                'snr': DETECTION_SNR.get(channel, 8.0),
                'tophat_radius': TOPHAT_RADIUS
            }
        
        detection_tasks.append((str(image_path), channel, DETECTION_METHOD, detection_kwargs))
    
    # Parallel spot detection
    all_coordinates = []
    channel_coords_dict = {}
    
    if detection_tasks:
        logger.info(f"Detecting spots in {len(detection_tasks)} channels...")
        with ProcessPoolExecutor(max_workers=min(len(detection_tasks), 4)) as executor:
            futures = [executor.submit(_detect_spots_in_channel, task) for task in detection_tasks]
            for future in tqdm(futures, desc='Detecting spots'):
                channel, coords, error = future.result()
                if error is None and len(coords) > 0:
                    channel_coords_dict[channel] = coords
                    all_coordinates.append(coords)
                    logger.info(f"  {channel}: {len(coords)} spots detected")
                elif error:
                    logger.warning(f"  {channel}: Error - {error}")
    
    if not all_coordinates:
        logger.warning("No spots detected in any channel!")
        return
    
    # Combine coordinates from all channels
    logger.info("Combining coordinates from all channels...")
    all_coords = np.vstack(all_coordinates)
    logger.info(f"Total coordinates before deduplication: {len(all_coords)}")
    
    # Remove exact duplicates (same pixel coordinates)
    coords_rounded = np.round(all_coords).astype(np.int32)
    _, unique_indices = np.unique(coords_rounded, axis=0, return_index=True)
    unique_coords = all_coords[unique_indices]
    logger.info(f"Total coordinates after removing exact duplicates: {len(unique_coords)}")
    
    # Stage 2: Intensity Reading
    logger.info("=" * 80)
    logger.info("Stage 2: Intensity Reading (tophat+3x3max)")
    logger.info("=" * 80)
    
    # Create intensity dataframe
    intensity_df = pd.DataFrame({'Y': unique_coords[:, 0], 'X': unique_coords[:, 1]})
    
    # Read intensities for each channel
    for channel in tqdm(CHANNELS, desc='Reading intensities'):
        image_path = stc_dir / f'cyc_1_{channel}.tif'
        if not image_path.exists():
            continue
        
        image = tifffile.imread(str(image_path))
        
        # Read intensities using tophat+3x3max
        intensities = read_intensity_tophat(
            image,
            unique_coords,
            tophat_radius=TOPHAT_RADIUS,
            search_radius=SEARCH_RADIUS
        )
        
        # Map channel names to PRISM standard names
        channel_map = {'cy5': 'R', 'TxRed': 'Ye', 'cy3': 'G', 'FAM': 'B'}
        intensity_df[channel_map.get(channel, channel)] = intensities
    
    logger.info(f"Intensity reading completed for {len(intensity_df)} spots")
    
    # Stage 3: Preprocessing and Thresholding
    logger.info("=" * 80)
    logger.info("Stage 3: Preprocessing and Thresholding")
    logger.info("=" * 80)
    
    # Crosstalk elimination
    if 'B' in intensity_df.columns and 'G' in intensity_df.columns:
        intensity_df['B'] = intensity_df['B'] - intensity_df['G'] * 0.25
        intensity_df['B'] = np.maximum(intensity_df['B'], 0)
    
    # Scale intensities
    if 'R' in intensity_df.columns:
        intensity_df['Scaled_R'] = intensity_df['R']
    if 'Ye' in intensity_df.columns:
        intensity_df['Scaled_Ye'] = intensity_df['Ye']
    if 'G' in intensity_df.columns:
        intensity_df['Scaled_G'] = intensity_df['G'] * 2.5
    if 'B' in intensity_df.columns:
        intensity_df['Scaled_B'] = intensity_df['B'] * 0.75
    
    # Calculate sum and apply thresholds
    intensity_cols = [c for c in ['Scaled_R', 'Scaled_Ye', 'Scaled_B'] if c in intensity_df.columns]
    if intensity_cols:
        intensity_df['sum'] = intensity_df[intensity_cols].sum(axis=1)
        
        # Apply threshold based on PRISM panel
        SUM_THRESHOLD = 800
        n_before = len(intensity_df)
        if PRISM_PANEL in ('PRISM30', 'PRISM45', 'PRISM63'):
            intensity_df = intensity_df[intensity_df['sum'] >= SUM_THRESHOLD]
        elif PRISM_PANEL in ('PRISM31', 'PRISM46', 'PRISM64'):
            G_THRESHOLD = 3
            G_ABS_THRESHOLD = 1000
            mask = (intensity_df['sum'] >= SUM_THRESHOLD) | \
                   ((intensity_df.get('Scaled_G', 0) / intensity_df['sum'] >= G_THRESHOLD) & 
                    (intensity_df.get('Scaled_G', 0) > G_ABS_THRESHOLD))
            intensity_df = intensity_df[mask]
        
        logger.info(f"Applied intensity threshold: {n_before} -> {len(intensity_df)} spots")
    
    # Stage 4: Final Deduplication
    logger.info("=" * 80)
    logger.info("Stage 4: Final Deduplication")
    logger.info("=" * 80)
    
    n_before_dedup = len(intensity_df)
    
    # Calculate score for deduplication (use sum intensity)
    if 'sum' in intensity_df.columns:
        intensity_df = deduplicate_dataframe(
            intensity_df,
            coordinate_columns=['Y', 'X'],
            threshold=DEDUP_THRESHOLD,
            sort_by='sum',
            ascending=False
        )
    else:
        intensity_df = deduplicate_dataframe(
            intensity_df,
            coordinate_columns=['Y', 'X'],
            threshold=DEDUP_THRESHOLD
        )
    
    logger.info(f"Deduplication: {n_before_dedup} -> {len(intensity_df)} spots")
    
    # Stage 5: Create Output Files
    logger.info("=" * 80)
    logger.info("Stage 5: Creating Output Files")
    logger.info("=" * 80)
    
    # Create index for matching position and intensity files
    intensity_df = intensity_df.reset_index(drop=True)
    intensity_df['index'] = intensity_df.index
    
    # Position file: Y, X, index
    position_df = intensity_df[['Y', 'X', 'index']].copy()
    position_file = read_dir / 'position.csv'
    position_df.to_csv(position_file, index=False)
    logger.info(f"Saved position file: {position_file} ({len(position_df)} spots)")
    
    # Intensity file: index, and all intensity columns
    intensity_cols = ['index'] + [c for c in intensity_df.columns 
                                  if c not in ['Y', 'X', 'index']]
    intensity_output_df = intensity_df[intensity_cols].copy()
    intensity_file = read_dir / 'intensity.csv'
    intensity_output_df.to_csv(intensity_file, index=False)
    logger.info(f"Saved intensity file: {intensity_file} ({len(intensity_output_df)} spots)")
    
    # Save parameters
    params = {
        'RUN_ID': RUN_ID,
        'PRISM_PANEL': PRISM_PANEL,
        'CHANNELS': CHANNELS,
        'DETECTION_METHOD': DETECTION_METHOD,
        'INTENSITY_METHOD': INTENSITY_METHOD,
        'TOPHAT_RADIUS': TOPHAT_RADIUS,
        'SEARCH_RADIUS': SEARCH_RADIUS,
        'DEDUP_THRESHOLD': DEDUP_THRESHOLD,
        'n_spots': len(intensity_df)
    }
    params_file = read_dir / 'readout_params.yaml'
    with open(params_file, 'w') as f:
        yaml.dump(params, f, default_flow_style=False)
    logger.info(f"Saved parameters: {params_file}")
    
    logger.info("=" * 80)
    logger.info("Multi-channel readout completed successfully!")
    logger.info(f"Output files:")
    logger.info(f"  - {position_file}")
    logger.info(f"  - {intensity_file}")
    logger.info("=" * 80)
    
    return position_df, intensity_output_df


if __name__ == '__main__':
    # Copy this file to the readout directory
    current_file_path = os.path.abspath(__file__)
    target_file_path = read_dir / os.path.basename(current_file_path)
    try:
        shutil.copy(current_file_path, target_file_path)
    except Exception as e:
        logger.warning(f"Could not copy script to readout directory: {e}")
    
    main(PRISM_PANEL=PRISM_PANEL, stc_dir=stc_dir, read_dir=read_dir)
